services:
  #############
  # Tailscale #
  #############
  filebrowser-ts: &ts
    image: tailscale/tailscale:latest
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/https.json
      - "TS_EXTRA_ARGS=--advertise-tags=tag:homelab --reset"
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module

  vaultwarden-ts: *ts
  trilium-ts: *ts

  ########
  # Apps #
  ########
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.domain.tld"
    volumes:
      - vaultwarden-data:/data/
    network_mode: service:vaultwarden-ts

  filebrowser:
    image: gtstef/filebrowser:beta
    container_name: filebrowser
    restart: unless-stopped
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml"
      FILEBROWSER_ADMIN_PASSWORD: ${FILEBROWSER_ADMIN_PASS}
      TZ: "Europe/Madrid"
    volumes:
      - /media/vieitesrpi/vieitesss/filebrowser:/folder
      - ./filebrowser:/home/filebrowser/data
    network_mode: service:filebrowser-ts

  trilium:
    image: triliumnext/trilium:stable
    environment:
      TRILIUM_NETWORK_PORT: "80"
    volumes:
      - trilium-data:/home/node/trilium-data
      - /media/vieitesrpi/vieitesss/filebrowser/dani:/media/vieitesrpi/dani
    network_mode: service:trilium-ts

volumes:
  vaultwarden-ts:
  vaultwarden-data:
  trilium-ts:
  trilium-data:
  filebrowser-ts:
