services:
  #############
  # Tailscale #
  #############
  filebrowser-ts: &ts
    image: tailscale/tailscale:latest
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    cap_add:
      - net_admin
      - sys_module
    volumes:
      - ${PWD}/tailscale:/config
      - /dev/net/tun:/dev/net/tun

  vaultwarden-ts: *ts

  ########
  # Apps #
  ########
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vaultwarden.burro-ph.ts.net"
    volumes:
      - vaultwarden-data:/data/
    network_mode: service:vaultwarden-ts

  filebrowser:
    image: gtstef/filebrowser:beta
    restart: unless-stopped
    environment:
      FILEBROWSER_CONFIG: "data/config.yaml"
      FILEBROWSER_ADMIN_PASSWORD: ${FILEBROWSER_ADMIN_PASS}
      TZ: "Europe/Madrid"
    volumes:
      - /media/vieitesrpi/vieitesss/filebrowser:/folder
      - ./filebrowser:/home/filebrowser/data
    network_mode: service:filebrowser-ts

volumes:
  vaultwarden-ts:
  vaultwarden-data:
  filebrowser-ts:
